---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 13.11.2025 00.00
---

---AddDir
---@param DIR string
---@return nil
function resource.AddDir(DIR)
    local GAMEFIL,GAMEDIR = file.Find(DIR.."/*","GAME")
    for k,v in pairs( GAMEDIR ) do resource.AddDir(DIR.."/"..v) end
    for k,v in pairs( GAMEFIL ) do resource.AddFile(DIR.."/"..v) end
end