---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 13.11.2025 00.37
---

Blocks = Blocks or {};

function GM:AddBlockCHud(Str)
    if (!table.HasValue(Blocks, Str)) then table.insert(Blocks, Str)
    end
end

hook.Add("HUDShouldDraw", "ShouldDraw", function(name)
    if (table.HasValue(Blocks, name)) then
        return false
    end
end)