---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 03.12.2025 21.56
---


if (SERVER) then
    util.AddNetworkString("WS_HELP")

    function GM:ShowHelp(pl)
        net.Start("WS_HELP")
        net.Send(pl)
    end
else
    net.Receive("WS_HELP",function()
        flipHelp();
    end)
end