---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 03.12.2025 21.45
---

surface.CreateFont( "ScoreboardFont", {size = 64, weight = 400, font = "coolvetica"} )